### ISSUE TITLE
URL-encoded labels are not decoded

### ISSUE THREAD

**Issue by matmai** [markmcavoy/androidtoken#14]
The label (issuer, account) has to be URL-encoded according to [RFC 3986](http://tools.ietf.org/html/rfc3986). The app should display the decoded label instead displaying an encoded hard to read label.

For example `Big%20Corporation:alice%40bigco.com` is not decoded and displayed as `Big Corporation:alice@bigco.com`.

See also https://github.com/google/google-authenticator/wiki/Key-Uri-Format#label

**Comment by markmcavoy** [comment]
fixed in the feature/nextVersion branch
