### ISSUE TITLE
Can't stay scrolled down on Android N

### ISSUE THREAD

**Issue by YellowApple** [markmcavoy/androidtoken#29]
With a list of tokens that's long enough to require scrolling, I'm unable to keep the app actually scrolled down; every time it decrements the progress bar to indicate when the codes expire, it pops back up to the top of the list.  This makes reading and using codes at the end of the list excruciatingly difficult.

Potentially-relevant info about the phone:
- **Model number:** Nexus 6P
- **Android version:** 7.0
- **ROM:** CopperheadOS
- **App installed from:** F-Droid (latest as of filing this report)

**Comment by shtrom** [comment]
Same issue on Nexus 5 (Hammerhead) with CM13.0 (Android 6.0.1).

**Comment by markmcavoy** [comment]
This is fixed in this commit aabe7924dbe511eec2a07f5d2abb60376fd50f4e in the features/nextVersion branch. Once I've completed all the changes this will be available in /master in the new version
