### ISSUE TITLE
Token Names should be urlunescaped.

### ISSUE THREAD

**Issue by 133794m3r** [markmcavoy/androidtoken#37]
Google authenticator takes the tokename and unescapes it for the token name it stores it as. So I would like to see androidtoken doing the same thing.

If no one else takes up this issue I may try my hand and modifying the code to include this feature once I get brave enough.

**Comment by markmcavoy** [comment]
This has already been implemented in the new branch that I'm working on that updates the app.

I hope to have the branch feature/nextVersion completed by Sept 2020 and then will merge back into the master branch. The new version has improved UI, Export functional and general improvements.
